# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3698e474849b82f14c586e398529b1b15f1c52f8061127ce220db9bc2e74b41ffcc43cae968dee2a0576a16831903cb5734331222b8559b0c0189ecc009d627b

test:
  secret_key_base: a2e3b3ad898b0f184d3a6734dbfb246947a6e9f92fe5b2f8353946419611a109feb58f7be7d00be8feb426f840fa67ca7b1097d787a0d7229639e1ac2f4f0c54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
